{
  "openapi": "3.0.1",
  "info": {
    "title": "gpu-docker-api",
    "description": "https://github.com/mayooot/gpu-docker-api",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "å®¹å™¨"
    },
    {
      "name": "å·"
    },
    {
      "name": "GPU"
    }
  ],
  "paths": {
    "/api/v1/containers": {
      "post": {
        "summary": "æäº¤å®¹å™¨ä¸ºé•œåƒ",
        "x-apifox-folder": "å®¹å™¨",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### æäº¤å®¹å™¨ä¸ºé•œåƒ\n\næè¿°ï¼šé•œåƒåç§°é»˜è®¤ä¸ºå®¹å™¨ IDã€‚",
        "tags": [
          "å®¹å™¨"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "newImageName": {
                    "type": "string",
                    "description": "å¯¼å‡ºçš„é•œåƒåç§°"
                  }
                },
                "required": [
                  "newImageName"
                ],
                "x-apifox-orders": [
                  "newImageName"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "newImageName": "advocate-0-12-27"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "container": {
                          "type": "string",
                          "description": "è¿›è¡Œ commit æ“ä½œçš„å®¹å™¨åç§°"
                        },
                        "imageName": {
                          "type": "string",
                          "description": "ç”Ÿæˆçš„é•œåƒåç§°"
                        }
                      },
                      "required": [
                        "container",
                        "imageName"
                      ],
                      "x-apifox-orders": [
                        "container",
                        "imageName"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "container": "advocate-0",
                        "imageName": "advocate-0-12-27"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326931-run"
      }
    },
    "/api/v1/containers/{name}/gpu": {
      "patch": {
        "summary": "æ›´æ”¹ GPU é…ç½®",
        "x-apifox-folder": "å®¹å™¨",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### æ›´æ”¹å®¹å™¨çš„ GPU é…ç½®\n\n> 1. å¦‚æœè°ƒç”¨æ¥å£å‰åï¼Œå®¹å™¨çš„ GPU æ•°é‡ä¸å˜ï¼Œé‚£ä¹ˆä¼šç›´æ¥è·³è¿‡ã€‚æ¯”å¦‚æœ‰å¡å®¹å™¨ä½¿ç”¨äº† 3 å¼ å¡ï¼Œè°ƒç”¨æ¥å£æ—¶ä¼ é€’çš„ gpuCount ä»ç„¶ä¸º 3ã€‚æ— å¡å®¹å™¨çš„ gpuCount ä¸º 0ï¼Œè°ƒç”¨æ¥å£æ—¶ä¼ é€’çš„ gpuCount ä»ç„¶ä¸º 0ã€‚\n> 2. å‡é™ GPU é…ç½®æ—¶ï¼Œä¼šé‡æ–°åˆ›å»ºä¸€ä¸ªå®¹å™¨ï¼Œæ¯”å¦‚ foo-0 å®¹å™¨çš„ gpuCount ä¸º 3ï¼Œå‡çº§åˆ° 5 å¼ å¡ï¼Œæ–°çš„å®¹å™¨åç§°ä¸º foo-1ã€‚æ­¤æ—¶ä¸èƒ½å†å¯¹ foo-0 è¿›è¡Œæ›´æ”¹ GPU/æ›´æ”¹ Volume çš„æ“ä½œï¼Œå› ä¸ºæœ€æ–°ç‰ˆæœ¬æ˜¯ foo-0ã€‚\n> 3. å¯ä»¥å°†æ— å¡å®¹å™¨å˜ä¸ºæœ‰å¡å®¹å™¨ï¼Œä¹Ÿå¯å°†æœ‰å¡å®¹å™¨è½¬ä¸ºæ— å¡å®¹å™¨ï¼Œå½“ç„¶ä¹Ÿå¯ä»¥å‡é™æœ‰å¡å®¹å™¨çš„ GPU å¡æ•°ã€‚",
        "tags": [
          "å®¹å™¨"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "è¦ä¿®æ”¹çš„å®¹å™¨çš„åç§°",
            "required": true,
            "example": "knockGpu-0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "gpuCount": {
                    "type": "integer",
                    "description": "è¦ä½¿ç”¨çš„GPU æ•°é‡"
                  }
                },
                "required": [
                  "gpuCount"
                ],
                "x-apifox-orders": [
                  "gpuCount"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "gpuCount": 5
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "description": "æ–°åˆ›å»ºçš„å®¹å™¨ ID"
                        },
                        "name": {
                          "type": "string",
                          "description": "æ–°åˆ›å»ºçš„å®¹å™¨åç§°"
                        }
                      },
                      "required": [
                        "id",
                        "name"
                      ],
                      "x-apifox-orders": [
                        "id",
                        "name"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "id": "f14e23c3b76bb25f67969ac5736f679c2aa09e7c90dd9d64d30629dd0b59c71d",
                        "name": "knockGpu-1"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326932-run"
      }
    },
    "/api/v1/containers/{name}/stop": {
      "patch": {
        "summary": "é‡å¯åŠ¨å®¹å™¨",
        "x-apifox-folder": "å®¹å™¨",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### é‡å¯å®¹å™¨\n\næè¿°ï¼šåœæ­¢çš„æ— å¡å®¹å™¨é‡å¯æ—¶ï¼Œç›´æ¥ docker restartã€‚\n\nåœæ­¢çš„æœ‰å¡å®¹å™¨é‡å¯æ—¶ï¼Œä¼šé‡æ–°ä¸ºå®ƒåˆ›å»ºä¸€ä¸ªæ–°å®¹å™¨ï¼ŒåŒæ—¶é‡æ–°ç”³è¯·å®ƒä¹‹å‰ä½¿ç”¨çš„æŒ‡å®šæ•°é‡çš„ GPUï¼ˆä½¿ç”¨çš„å¡å·å¯èƒ½å‘ç”Ÿå˜åŒ–ï¼Œä¾‹å¦‚ä¹‹å‰ä½¿ç”¨0ã€ 1ã€ 2 å·å¡ï¼Œæ–°å®¹å™¨å¯èƒ½ä½¿ç”¨ 3ã€ 4ã€ 5 å·å¡ï¼‰ã€‚\n\nâš ï¸**ä¸ç”¨æ‹…å¿ƒçš„æ˜¯ï¼Œå®ƒå’Œä¹‹å‰çš„å®¹å™¨ä¸€æ¨¡ä¸€æ ·ï¼Œåªæ˜¯çœ‹èµ·æ¥å®¹å™¨åç§°æœ‰äº›å˜åŒ–ã€‚**",
        "tags": [
          "å®¹å™¨"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "éœ€è¦é‡å¯çš„å®¹å™¨åç§°",
            "required": true,
            "example": "sarcastic-0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "description": "æœ‰å¡å®¹å™¨â€œé‡å¯â€åæ–°åˆ›å»ºçš„å®¹å™¨ ID"
                        },
                        "name": {
                          "type": "string",
                          "description": "æœ‰å¡å®¹å™¨â€œé‡å¯â€åæ–°åˆ›å»ºçš„å®¹å™¨åç§°"
                        }
                      },
                      "required": [
                        "id",
                        "name"
                      ],
                      "x-apifox-orders": [
                        "id",
                        "name"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "id": "cc19da17f809b19e05f5baf85b873248d70de0903f390e85fb08cbc1cda29000",
                        "name": "sarcastic-1"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326934-run"
      }
    },
    "/api/v1/containers/{name}/volume": {
      "patch": {
        "summary": "æ›´æ”¹ Volume é…ç½®",
        "x-apifox-folder": "å®¹å™¨",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### æ›´æ”¹å®¹å™¨çš„ Volume é…ç½®\n\n> 1. å˜æ›´çš„æŒ‚è½½ä¿¡æ¯å¿…é¡»ä¸º Docker Volume ç±»å‹çš„å·ï¼Œå› ä¸ºé Docker Volume ç±»å‹çš„æŒ‚è½½ï¼Œä¾‹å¦‚ NFS ç›®å½•æŒ‚è½½åˆ°å®¹å™¨å†…éƒ¨ï¼Œæ‰©å®¹/ç¼©å®¹ã€æ•°æ®çš„é”€æ¯ä¸æ˜¯ç”± Docker ç®¡ç†çš„ã€‚\n>\n> 2. å¦‚æœä¼ é€’çš„ oldBind å’Œ newBind ç›¸åŒï¼Œä¼šç›´æ¥è·³è¿‡ã€‚\n>\n> 3. è¿™é‡Œçš„å¤„ç†æ–¹å¼å’Œ`æ›´æ”¹å®¹å™¨çš„ GPU é…ç½®`ä¸åŒï¼Œå…·ä½“åœ¨`æ›´æ”¹å‰åèµ„æºæ²¡æœ‰å‘ç”Ÿå˜åŒ–`è¿™ä¸€æƒ…å†µã€‚\n>\n>    æ›´æ”¹ GPU æ—¶ï¼Œå¦‚æœæ›´æ”¹å‰åå¡çš„æ•°é‡ä¸€æ ·ï¼Œå°±è·³è¿‡ã€‚\n>\n>    è€Œå¯¹äº Volume æ¥è¯´ï¼Œåˆ¤æ–­`æ›´æ”¹å‰åå®¹é‡æ˜¯å¦å‘ç”Ÿå˜åŒ–`ï¼Œå¤„ç†é€»è¾‘åœ¨ `æ›´æ”¹ Volume å¤§å°`çš„æ¥å£ã€‚\n>\n>    æ‰€ä»¥ä½¿ç”¨è¯¥æ¥å£æ—¶ï¼Œä¼ é€’çš„åº”è¯¥æ˜¯æ‰©å®¹/ç¼©å®¹å¥½çš„ Volumeï¼ˆæˆ–è€…ä¸€å¼ æ–°çš„ Volumeï¼Œä¸è¿‡æ²¡æµ‹è¯•è¿‡è¿™ç§æƒ…å†µæ˜¯å¦å¯ç”¨ğŸ˜¢ï¼‰ã€‚",
        "tags": [
          "å®¹å™¨"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "è¦ä¿®æ”¹çš„å®¹å™¨åç§°",
            "required": true,
            "example": "marital-0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "å·çš„ç±»å‹ï¼Œç›®å‰åªæ”¯æŒ volumeï¼Œä¹Ÿå°±æ˜¯ docker volume createçš„å·"
                  },
                  "oldBind": {
                    "type": "object",
                    "properties": {
                      "src": {
                        "type": "string",
                        "description": "æ—§çš„ volume åç§°"
                      },
                      "dest": {
                        "type": "string",
                        "description": "æ—§çš„å®¹å™¨å†…çš„æŒ‚è½½åœ°å€"
                      }
                    },
                    "required": [
                      "src",
                      "dest"
                    ],
                    "x-apifox-orders": [
                      "src",
                      "dest"
                    ],
                    "description": "å®¹å™¨ç›®å‰ä½¿ç”¨çš„å·ç»‘å®šä¿¡æ¯",
                    "x-apifox-ignore-properties": []
                  },
                  "newBind": {
                    "type": "object",
                    "properties": {
                      "src": {
                        "type": "string",
                        "description": "æ–°çš„ volume åç§°"
                      },
                      "dest": {
                        "type": "string",
                        "description": "æ–°çš„å®¹å™¨å†…çš„æŒ‚è½½åœ°å€"
                      }
                    },
                    "required": [
                      "src",
                      "dest"
                    ],
                    "x-apifox-orders": [
                      "src",
                      "dest"
                    ],
                    "description": "å®¹å™¨å°†è¦ä½¿ç”¨çš„å·ç»‘å®šä¿¡æ¯",
                    "x-apifox-ignore-properties": []
                  }
                },
                "required": [
                  "type",
                  "oldBind",
                  "newBind"
                ],
                "x-apifox-orders": [
                  "type",
                  "oldBind",
                  "newBind"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "type": "volume",
                "oldBind": {
                  "src": "aerialVol-0",
                  "dest": "/root/aerialVol"
                },
                "newBind": {
                  "src": "aerialVol-1",
                  "dest": "/root/aerialVol"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "description": "æ–°å®¹å™¨çš„ ID"
                        },
                        "name": {
                          "type": "string",
                          "description": "æ–°å®¹å™¨çš„åç§°"
                        }
                      },
                      "required": [
                        "id",
                        "name"
                      ],
                      "x-apifox-orders": [
                        "id",
                        "name"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "id": "671eacb8514c92fa62e296785c1164b0a70f4c5fc28b525a210f870acef94e2b",
                        "name": "marital-1"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326935-run"
      }
    },
    "/api/v1/containers/{name}/execute": {
      "post": {
        "summary": "æ‰§è¡Œå‘½ä»¤",
        "x-apifox-folder": "å®¹å™¨",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### å®¹å™¨å†…æ‰§è¡Œå‘½ä»¤\n\næè¿°ï¼šç›¸å½“äº docker execï¼Œä½†æ˜¯ä¸èƒ½å‘åœ¨å®¿ä¸»æœºä¸€æ ·è¿›å…¥å®¹å™¨ï¼Œåªèƒ½å°†æ ‡å‡†è¾“å‡ºè¿”å›ï¼Œå½“ä½ ä¼ é€’ä¸€äº›å‘½ä»¤ç»™å®¹å™¨æ—¶ã€‚",
        "tags": [
          "å®¹å™¨"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "è¦æ‰§è¡Œå‘½ä»¤çš„å®¹å™¨åç§°",
            "required": true,
            "example": "dilute-0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "cmd": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "description": "å®¹å™¨ä¸­è¦æ‰§è¡Œçš„å‘½ä»¤"
                  }
                },
                "required": [
                  "cmd"
                ],
                "x-apifox-orders": [
                  "cmd"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "cmd": [
                  "nvidia-smi"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "stdout": {
                          "type": "string",
                          "description": "å‘½ä»¤çš„æ ‡å‡†è¾“å‡º"
                        }
                      },
                      "required": [
                        "stdout"
                      ],
                      "x-apifox-orders": [
                        "stdout"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "stdout": "Wed Dec 27 09:11:22 2023       \n+-----------------------------------------------------------------------------+\n| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |\n|-------------------------------+----------------------+----------------------+\n| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n|                               |                      |               MIG M. |\n|===============================+======================+======================|\n|   0  NVIDIA A100 80G...  On   | 00000000:39:00.0 Off |                    0 |\n| N/A   39C    P0    47W / 300W |      0MiB / 81920MiB |      0%      Default |\n|                               |                      |             Disabled |\n+-------------------------------+----------------------+----------------------+\n                                                                               \n+-----------------------------------------------------------------------------+\n| Processes:                                                                  |\n|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |\n|        ID   ID                                                   Usage      |\n|=============================================================================|\n|  No running processes found                                                 |\n+-----------------------------------------------------------------------------+\n"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326936-run"
      }
    },
    "/api/v1/containers/{name}": {
      "delete": {
        "summary": "åˆ é™¤å®¹å™¨",
        "x-apifox-folder": "å®¹å™¨",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### åˆ é™¤å®¹å™¨\n\næè¿°ï¼šåˆ é™¤æœ‰å¡å®¹å™¨æ—¶ï¼Œä¼šé‡Šæ”¾å®ƒæ‰€å ç”¨çš„ GPU èµ„æºï¼Œå¦‚æœæŒ‡å®šäº† delEtcdInfoAndVersionRecord å‚æ•°ä¸º trueï¼Œé‚£ä¹ˆåˆ é™¤å®¹å™¨æ—¶ä¹Ÿä¼šåˆ é™¤æ‰ ETCD å’Œ VersionMap ä¸­å…³äºå®ƒçš„è®°å½•ã€‚\n\né€šè¿‡ä¸€ä¸ªå…·ä½“çš„ä¾‹å­æ¥è§£é‡Šï¼Œæ¯”å¦‚å½“å‰æœ‰ä¸€ä¸ª foo-0 å®¹å™¨ï¼Œå®ƒç»è¿‡ä¸€æ¬¡å‡çº§ GPU é…ç½®ï¼Œå˜æˆäº† foo-1ã€‚\n\næ­¤æ—¶ï¼Œè¦åˆ é™¤ foo-1ï¼Œå¦‚æœæŒ‡å®šäº† delEtcdInfoAndVersionRecord ä¸º trueï¼Œé‚£ä¹ˆ ETCD ä¸­å…³äº foo çš„æè¿°ä¼šè¢«åˆ é™¤ï¼Œä»¥ä¸ºè®°å½•ç‰ˆæœ¬çš„ Map ä¸­ä¼šç§»é™¤ fooã€‚å°±å¥½åƒ foo-0ã€foo-1 ä»æ¥æ²¡æœ‰æ¥è¿‡ã€‚\n\nå½“ç„¶ foo-0 è¿˜æ²¡æœ‰è¢«åˆ é™¤ï¼Œå½“ä½ æŠŠ foo-0 åˆ é™¤æ—¶ï¼Œä½ å°±å¯ä»¥å†æ¬¡ç”¨ foo ä½œä¸ºåå­—åˆ›å»ºå®¹å™¨ï¼Œæ–°çš„æè¿°ä¼šè¢«æ·»åŠ åˆ° ETCDï¼Œç„¶å {k: foo, v: 0} ä¼šè¢«æ·»åŠ åˆ° VersionMap ä¸­ã€‚\n\nå¦‚æœ delEtcdInfoAndVersionRecordä¸º falseï¼Œæˆ‘ä»¬åˆ é™¤äº† foo-1ï¼Œæ­¤æ—¶æˆ‘ä»¬ä»ç„¶å¯ä»¥åœ¨ foo-1 çš„åŸºç¡€ä¸Šç»§ç»­å˜æ›´é…ç½®ï¼Œç”Ÿæˆä¸€ä¸ª foo-2ã€‚è¿™é€‚ç”¨äºé‡Šæ”¾èµ„æºã€‚\n\næ‰€ä»¥ï¼Œå¦‚æœè¦å•çº¯çš„é‡Šæ”¾èµ„æºï¼ŒdelEtcdInfoAndVersionRecord åº”ä¸º falseã€‚å¦‚æœç¡®å®šè¿™ä¸ªè¦æŠ¹é™¤æ‰ä¸€ä¸ªå®¹å™¨çš„å†å²ç‰ˆæœ¬ï¼Œåº”ä¸º trueã€‚\n\n<!--TODOï¼šå…¶å®å¯ä»¥åªä¼ å…¥ fooï¼Œå¦‚æœdelEtcdInfoAndVersionRecordä¸º trueï¼Œé‚£ä¹ˆå°±åˆ é™¤ ETCDã€VersionMap ä¸­çš„æ•°æ®ï¼Œç„¶åä¾æ¬¡åˆ é™¤ foo-0ã€foo-1... foo-nã€‚ç„¶åæ²¡æœ‰å•ç‹¬çš„åˆ é™¤å®¹å™¨ï¼Œå¯èƒ½æ¯”è¾ƒå¥½ã€‚ğŸ¤”-->",
        "tags": [
          "å®¹å™¨"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "éœ€è¦åˆ é™¤çš„å®¹å™¨åç§°",
            "required": true,
            "example": "sarcastic-0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "force": {
                    "type": "boolean",
                    "description": "æ˜¯å¦å¼ºåˆ¶åˆ é™¤"
                  },
                  "delEtcdInfoAndVersionRecord": {
                    "type": "boolean",
                    "description": "æ˜¯å¦åˆ é™¤ ETCD å’Œ VersionMap ä¸­çš„å®¹å™¨ä¿¡æ¯"
                  }
                },
                "required": [
                  "force",
                  "delEtcdInfoAndVersionRecord"
                ],
                "x-apifox-orders": [
                  "force",
                  "delEtcdInfoAndVersionRecord"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "force": true,
                "delEtcdInfoAndVersionRecord": true
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "null"
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326937-run"
      }
    },
    "/api/v1/gpus": {
      "get": {
        "summary": "æŸ¥çœ‹GPUä½¿ç”¨çŠ¶æ€",
        "x-apifox-folder": "GPU",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### æŸ¥çœ‹ GPU ä½¿ç”¨æƒ…å†µ\n\næè¿°ï¼škeyï¼šGPU UUID  valueï¼šå ç”¨æƒ…å†µï¼Œ0 ä»£è¡¨æœªè¢«å ç”¨ï¼Œ1 ä»£è¡¨å·²è¢«å ç”¨",
        "tags": [
          "GPU"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "gpuStatus": {
                          "type": "object",
                          "properties": {
                            "GPU-04adce59-e7fc-19ed-6800-bc09e5f8fa31": {
                              "type": "integer"
                            },
                            "GPU-281d9730-5a26-7c56-12fb-3a3d5a24ab68": {
                              "type": "integer"
                            },
                            "GPU-36009026-9470-a2e0-73d3-222a63b82e4e": {
                              "type": "integer"
                            },
                            "GPU-7a42be89-64fe-5383-c7be-49d199a96b3d": {
                              "type": "integer"
                            },
                            "GPU-82fbe07b-200b-1d4c-4fbe-b0b54db86be5": {
                              "type": "integer"
                            },
                            "GPU-bc85a406-0357-185f-a56c-afb49572bdbe": {
                              "type": "integer"
                            },
                            "GPU-c6b3ca5f-c1ac-8171-582b-737b70a6bbce": {
                              "type": "integer"
                            },
                            "GPU-dc6d913c-8df4-a9a4-49e6-b82fcba5a6f9": {
                              "type": "integer"
                            }
                          },
                          "required": [
                            "GPU-04adce59-e7fc-19ed-6800-bc09e5f8fa31",
                            "GPU-281d9730-5a26-7c56-12fb-3a3d5a24ab68",
                            "GPU-36009026-9470-a2e0-73d3-222a63b82e4e",
                            "GPU-7a42be89-64fe-5383-c7be-49d199a96b3d",
                            "GPU-82fbe07b-200b-1d4c-4fbe-b0b54db86be5",
                            "GPU-bc85a406-0357-185f-a56c-afb49572bdbe",
                            "GPU-c6b3ca5f-c1ac-8171-582b-737b70a6bbce",
                            "GPU-dc6d913c-8df4-a9a4-49e6-b82fcba5a6f9"
                          ],
                          "x-apifox-orders": [
                            "GPU-04adce59-e7fc-19ed-6800-bc09e5f8fa31",
                            "GPU-281d9730-5a26-7c56-12fb-3a3d5a24ab68",
                            "GPU-36009026-9470-a2e0-73d3-222a63b82e4e",
                            "GPU-7a42be89-64fe-5383-c7be-49d199a96b3d",
                            "GPU-82fbe07b-200b-1d4c-4fbe-b0b54db86be5",
                            "GPU-bc85a406-0357-185f-a56c-afb49572bdbe",
                            "GPU-c6b3ca5f-c1ac-8171-582b-737b70a6bbce",
                            "GPU-dc6d913c-8df4-a9a4-49e6-b82fcba5a6f9"
                          ],
                          "description": "GPU ä½¿ç”¨æƒ…å†µ",
                          "x-apifox-ignore-properties": []
                        }
                      },
                      "required": [
                        "gpuStatus"
                      ],
                      "x-apifox-orders": [
                        "gpuStatus"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "gpuStatus": {
                          "GPU-04adce59-e7fc-19ed-6800-bc09e5f8fa31": 0,
                          "GPU-281d9730-5a26-7c56-12fb-3a3d5a24ab68": 0,
                          "GPU-36009026-9470-a2e0-73d3-222a63b82e4e": 0,
                          "GPU-7a42be89-64fe-5383-c7be-49d199a96b3d": 0,
                          "GPU-82fbe07b-200b-1d4c-4fbe-b0b54db86be5": 0,
                          "GPU-bc85a406-0357-185f-a56c-afb49572bdbe": 0,
                          "GPU-c6b3ca5f-c1ac-8171-582b-737b70a6bbce": 0,
                          "GPU-dc6d913c-8df4-a9a4-49e6-b82fcba5a6f9": 0
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326938-run"
      }
    },
    "/api/v1/volumes": {
      "post": {
        "summary": "åˆ›å»ºå·",
        "x-apifox-folder": "å·",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### åˆ›å»ºæŒ‡å®šå¤§å°çš„ Volume\n\næè¿°ï¼šå¤§å°æ”¯æŒçš„å•ä½æœ‰ï¼šKB, MB, GB, TBï¼ˆä¸åŒºåˆ†å¤§å°å†™ï¼‰",
        "tags": [
          "å·"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Volume åç§°"
                  },
                  "size": {
                    "type": "string",
                    "description": "å®¹é‡å¤§å°"
                  }
                },
                "required": [
                  "name",
                  "size"
                ],
                "x-apifox-orders": [
                  "name",
                  "size"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "name": "rubVol",
                "size": "20GB"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "description": "åˆ›å»ºå‡ºæ¥çš„ Volume åç§°"
                        },
                        "size": {
                          "type": "string",
                          "description": "åˆ›å»ºå‡ºæ¥çš„ Volume å®¹é‡å¤§å°"
                        }
                      },
                      "required": [
                        "name",
                        "size"
                      ],
                      "x-apifox-orders": [
                        "name",
                        "size"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "name": "rubVol-0",
                        "size": "20GB"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326940-run"
      }
    },
    "/api/v1/volumes/{name}": {
      "delete": {
        "summary": "åˆ é™¤å·",
        "x-apifox-folder": "å·",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "",
        "tags": [
          "å·"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "è¦åˆ é™¤çš„ Volume åç§°",
            "required": true,
            "example": "rubVol-2",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "null"
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326941-run"
      }
    },
    "/api/v1/volumes/{name}/size": {
      "patch": {
        "summary": "æ›´æ”¹å·å¤§å°",
        "x-apifox-folder": "å·",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "### æ›´æ”¹ Volume çš„å¤§å°\n\n> 1. æ— è®ºæ‰©å®¹/ç¼©å®¹ï¼Œå¦‚æœæ“ä½œå‰åå¤§å°ä¸å˜ï¼Œé‚£ä¹ˆå°±ä¼šè·³è¿‡ã€‚\n>\n>    ä¾‹å¦‚å½“å‰ Volume å¤§å°ä¸º 20GBï¼Œæ‰©å®¹/ç¼©å®¹åè¿˜æ˜¯20GBã€‚\n>\n> 2. æ›´æ”¹å¤§å°æ—¶ï¼Œä¼šé‡æ–°åˆ›å»ºä¸€ä¸ª Volumeï¼Œæ¯”å¦‚ foo-0 çš„å¤§å°ä¸º 10GBï¼Œæ‰©å®¹æˆ 20GBï¼Œæ–°çš„ Volume åç§°ä¸º foo-1ã€‚æ­¤æ—¶ä¸èƒ½å†å¯¹ foo-0 è¿›è¡Œæ›´æ”¹ Volume æ“ä½œï¼Œå› ä¸ºæœ€æ–°çš„ç‰ˆæœ¬æ˜¯ foo-1ã€‚\n",
        "tags": [
          "å·"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "è¦ä¿®æ”¹çš„ Volume åç§°",
            "required": true,
            "example": "rubVol-0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "size": {
                    "type": "string",
                    "description": "ä¿®æ”¹åçš„ Volume å®¹é‡å¤§å°"
                  }
                },
                "required": [
                  "size"
                ],
                "x-apifox-orders": [
                  "size"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "size": "50GB"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "msg": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "description": "æ–°åˆ›å»ºçš„ Volume åç§°"
                        },
                        "size": {
                          "type": "string",
                          "description": "æ–°åˆ›å»ºçš„ Volume å®¹é‡å¤§å°"
                        }
                      },
                      "required": [
                        "name",
                        "size"
                      ],
                      "x-apifox-orders": [
                        "name",
                        "size"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "msg",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "code": 200,
                      "msg": "success",
                      "data": {
                        "name": "rubVol-1",
                        "size": "50GB"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3830507/apis/api-137326942-run"
      }
    }
  },
  "components": {
    "schemas": {}
  },
  "servers": [
    {
      "url": "http://127.0.0.1:2378",
      "description": "Develop Env"
    }
  ]
}